spring.application.name=Techstore

spring.datasource.url=jdbc:mysql://localhost:3306/techstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=admin
spring.datasource.password=phuc2003@

# ==========================
# CẤU HÌNH JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.thymeleaf.cache=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ==========================
# CẤU HÌNH PORT
# ==========================
server.port=8080

# ==========================
# CẤU HÌNH ENCODING
# ==========================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
# ==========================
# CẤU HÌNH mail
# ==========================

logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web.servlet.view=DEBUG

# sendgrid.api-key=${SENDGRID_API_KEY}
# ==========================
# CẤU HÌNH sepay
# ==========================
sepay.merchant-id=SP-TEST-NHAB5AAA
sepay.secret-key=spsk_test_dtQxzaDJPiKPHaQWRKMs5zQ7T3MoYFS

# Ngrok URL hoặc localhost khi test backend
sepay.ipn-url=https://unitable-dottie-elidible.ngrok-free.dev/api/sepay/webhook



# Sandbox API
sepay.endpoint=https://api.sandbox.sepay.vn





